name: Test

on:
  - push

jobs:
  build:
    name: Python ${{ matrix.python-version }} / ${{ matrix.django-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
        django-version:
          - '>=3.2,<4.0'
          - '>=4.2,<5.0'

    env:
      DJANGO_VERSION: ${{ matrix.django-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install redis
        run: ./install_redis.sh

      - name: Run tests
        run: make test
